before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: eWa4rp11B4THnPZlcSZDL3/+Y05lmmqqgKKOJ9dSBNtJ1gZqevh1Xsx5HHwWxGwiRD/6WkyVXFk7VhPFCunS6StH43Jy4/vGSz9rZfV7Y3CfhoMakC0TCmq3M9x4+272TY97E7kEsiJvmShiKZwKfwuNlN+bL/DXYpGR2BU3N5VhEeQ9+rfLsXlm4GwLY1TGfshKfPxRhVWeX+fFFP4grvrLS+OpebcO7UgGeV0l4KvJANwR/o3ftHwcJY3dGzARmPSCDieNtiWNlRskjqAVSu6fWRDFo36C2+3QsHpjUgwDZH1g+WYorou2ioXofBgDRSR+c9hjpb7GOQDwDp1dD6PycKm3DvEuJtmpgxn1VbNefAUWm/+ZNXgxKxCDgbvpuadljx1rof/XhtLd1wde+0uP2TVv/juiMDiqe8Ap49JUUwPOgUIHkQPdk/9ZnbGzM+/rHVZklLlaar8T8KihO0tEzJavqSrot69xfISuHIf2i1dqBVQr1YEVYhSLjQUJE5DR1EArf6EvdW5uf5Vmb96gCa1bOBTd1nF11Tx/Bcug1sB4FqtOP2+rnBpMCZMGfs2nGeorzIRamVoVohyVcIrFB+8C1PAkvrQsEvmsB9a6LSJWA3exfN5nptw/55Govk9VpitcZkxhMBZCCGOieQMbXUSRl+p6N02H7DyrsEM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
